### ISSUE TITLE
Release 11.9 introduces binary incompatibility (NoSuchMethodError)

### ISSUE THREAD

**Issue by metteo** [OpenFeign/feign#1670] opened 2022-06-29 08:46 UTC
Refactoring of some methods from Feign.Builder into BaseBuilder caused some incompatibilities on bytecode level. I guess there is no way to fix this now, but I suggest plugging in some tool that automatically detects such problems during CI: https://lvc.github.io/japi-compliance-checker/

EDIT: Moved the method from the title for better indexing: `Feign.Builder.contract(Contract)`

**Comment by velo** [comment] 2022-06-29 11:28
How can that happen?!

**Comment by metteo** [comment] 2022-06-29 12:16
Will try to prepare a mini test project after work today.

**Comment by pstorch** [comment] 2022-07-04 07:55
Maybe related, we got this NoSuchMethodError with Feign 1.19:

`Caused by: java.lang.NoSuchMethodError: 'feign.Feign$Builder feign.Feign$Builder.options(feign.Request$Options)'`

**Comment by velo** [comment] 2022-07-04 08:41
> Will try to prepare a mini test project after work today. Long story short, project compiled with version 1.19 but run with 1.18 on classpath (without recompiling) will throw the Exception.


Why compile with .19 and run with .18?

I would understand the other way around...

**Comment by velo** [comment] 2022-07-04 09:33
@freddidierRTE By any chance you mixing feign versions too?

**Comment by metteo** [comment] 2022-07-04 11:52
We have library which was updated by renovate to 1.19. After upgrading that library in an application which has maven dependency management set to 1.18 the project would not run. Only after upgrading Feign in the app at the same time as the library, it worked.

**Comment by freddidierRTE** [comment] 2022-07-04 12:27
> @freddidierRTE By any chance you mixing feign versions too?

You are right , i realized i m using openfeign 1.19 for my application but spring-cloud-starter-openfeign for my test code which is still on openfeign 1.18 

Thanks !

**Comment by velo** [comment] 2022-07-04 21:17
Do you guys think this help/solves this problem?
https://github.com/OpenFeign/feign#mavens-bill-of-material-bom

**Comment by pstorch** [comment] 2022-07-08 04:58
For us it's solved. We found another lib which referenced the 11.8. After upgrading that one our project build again.

**Comment by erwinw** [comment] 2022-07-10 10:38
This is causing some major headaches for us; any chance this can be addressed in a follow-up version?

**Comment by velo** [comment] 2022-07-10 18:11
Mixing feign version can have unintended consequences.

Make sure to have ONE single version on classpath
https://github.com/OpenFeign/feign/issues/1670#issuecomment-1174382555

**Closed by velo** 2022-07-10 18:11 UTC

**Comment by erwinw** [comment] 2022-07-10 20:16
> Mixing feign version can have unintended consequences.
> 
> 
> 
> Make sure to have ONE single version on classpath
> 
> https://github.com/OpenFeign/feign/issues/1670#issuecomment-1174382555

I understand this would be ideal - as would not introducing breaking changes in a feature release - yet here we are. Just closing this issue as if nothing happened is imho a really unfortunate response and ignores the mistake; claiming "you're holding it wrong" does nothing to help your users here.

**Comment by velo** [comment] 2022-07-10 20:52
Well, project is 100% run an supported by volunteer work. You are more than welcome to help out with a solution.

I honestly don't see how to get partial versioning upgrades to work.

**Comment by velo** [comment] 2022-07-11 01:23
BTW, @erwinw if you have an example that doesn't include mixed feign version, I can try to help, like I did with https://github.com/Skyterix1991/FurrifyWS-Storage/pull/427

but just complaining about it shouldn't have happened doesn't help at all

**Comment by velo** [comment] 2022-07-15 01:50
this should help, at least helped with a springboot example that was brought to my attention 
#1689 

if someone else has details about bytecode incompatibilities I will gladly fix it

**Comment by velo** [comment] 2022-07-21 21:24
Release is out
https://github.com/OpenFeign/feign/releases/tag/11.9.1

**Comment by sahiloberoi123** [comment] 2025-01-08 12:08
Hi, this might be the same issue right ?
Caused by: java.lang.NoSuchMethodError: 'void feign.FeignException.<init>(int, java.lang.String, byte[])' at  .FeignErrorDecoder.decode(FeignErrorDecoder.kt:32)

Can anyone help here, moving from 11.8 to 11.9 will resolve this right ?
