### ISSUE TITLE
GET request with dynamic header bug

### ISSUE THREAD

**Issue by DanielYWoo** [OpenFeign/feign#594] opened 2017-10-02 04:27 UTC
In the following example, the header parameter "tenant-id" will be added to the request body and change the GET to POST, which is very wired.

```
    @RequestLine("GET /templates?lastTemplateId={lastTemplateId}&rowNum={rowNum}")
    @Headers({"tenant-id:{tenantId}"})
    GetTemplatesResponse getTemplates(
            @Param("tenantId") String tenantId,
            @Param("lastTemplateId") String lastTemplateId,
            @Param("rowNum") int rowNum) throws ServiceException;
```

expected:
GET /templates

actual:
POST /templates
{"tenantId": "some tenant id"}

**Comment by adriancole** [comment] 2017-10-02 05:51
maybe verify with a MockWebServer unit test?

**Comment by kdavisk6** [comment] 2019-08-12 14:22
Closing this issue.  We have test cases in the application that check this now and we are not able to reproduce.  If you have a test case that can show us this, feel free to re-open

**Closed by kdavisk6** 2019-08-12 14:22 UTC
Labels: needs info
