### ISSUE TITLE
400 returning when calling elasticsearch from feign

### ISSUE THREAD

**Issue by jaylucas** [OpenFeign/feign#424] opened 2016-07-29 20:39 UTC
So I have a basic request to a locally running instance of elasticsearch

```
    @RequestLine("GET /_search?q=body:{body}")
    public ElasticGetResponse getResumes(@Param("body") String body);
```

Here is what I get through the logger:

```
[ElasticSearchService#getResumes] ---> GET http://localhost:9200/_search?q=body%3A%7Bbody%7D HTTP/1.1
[ElasticSearchService#getResumes] Content-Length: 21
[ElasticSearchService#getResumes] 
[ElasticSearchService#getResumes] {
  "body" : "phil"
}
[ElasticSearchService#getResumes] ---> END HTTP (21-byte body)
[ElasticSearchService#getResumes] <--- HTTP/1.1 400 Bad Request (154ms)
[ElasticSearchService#getResumes] Content-Length: 470
[ElasticSearchService#getResumes] Content-Type: application/json; charset=UTF-8
[ElasticSearchService#getResumes] 
[ElasticSearchService#getResumes] {"error":{"root_cause":    [{"type":"search_parse_exception","reason":"failed to parse search source. unknown search element [body]","line":2,"col":3}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"1","node":"rOGZzEghRVacdIRh_E9Wog","reason":{"type":"search_parse_exception","reason":"failed to parse search source. unknown search element [body]","line":2,"col":3}}]},"status":400}
[ElasticSearchService#getResumes] <--- END HTTP (470-byte body)
```

Now of course I dont get the problem when I `curl` the same endpoint

```
curl 'http://localhost:9200/_search?q=body:phil'
```

returns the correct docs

My question is why does feign hate that colon? When I have `_search?q=phil` it works....

**Comment by adriancole** [comment] 2016-07-29 20:53
maybe do a curl -v? also, if it doesn't look obvious, you could use
wireshark or something to get exactly what went on the wire from feign (ex
this would show a Host header value)

**Comment by jaylucas** [comment] 2016-07-29 22:20
So this is what I got with the `curl -v`

    > GET /_search?q=id:5 HTTP/1.1
    > User-Agent: curl/7.37.1
    > Host: localhost:9200
    > Accept: */*
    > 
    < HTTP/1.1 200 OK
    < Content-Type: application/json; charset=UTF-8
    < Content-Length: 884
    < 
     * Connection #0 to host localhost left intact
    {"took":4,"timed_out":false,"_shards": .........

Wasn't sure about the headers so I added

        @RequestLine("GET /_search?q=body:{body}")
        @Headers("Content-Type: application/json; charset=UTF-8")
        public ElasticGetResponse getResumes(@Param("body") String body);

No luck :(

I tried using wire shark to view the url but unfortunately I suck at wireshark. I can see the packets (SYN, ACK, FIN) but I can't determine the url past `127.0.0.1`

**Comment by jaylucas** [comment] 2016-08-03 15:18
Any word on this?

**Comment by adriancole** [comment] 2016-08-03 18:28
sorry.. off radar as in conference right now.

**Comment by jaylucas** [comment] 2016-08-03 20:14
:(

**Comment by adriancole** [comment] 2016-08-03 21:04
ok looking at your dump, it looks like a request body is being created, eventhough this is a GET request! This sounds very strange to me.

**Comment by adriancole** [comment] 2016-08-03 21:05
ex the below is showing a json body being made. The code you pasted doesn't seem like it should be creating a json body. Is there anything else (perhaps about how feign is constructed), which might explain this?

```
[ElasticSearchService#getResumes] ---> GET http://localhost:9200/_search?q=body%3A%7Bbody%7D HTTP/1.1
[ElasticSearchService#getResumes] Content-Length: 21
[ElasticSearchService#getResumes] 
[ElasticSearchService#getResumes] {
  "body" : "phil"
}
```

**Comment by jaylucas** [comment] 2016-08-03 22:59
This is what I have:

    public class ElasticSearchFactory {
       public static ElasticSearchService elasticSearchService() {
            final String host = "http://localhost:9200";

            return Feign.builder()
                .encoder(new JacksonEncoder())
                .decoder(new JacksonDecoder())
                .logger(new Logger.JavaLogger().appendToFile("/logs/http.log"))
                .logLevel(Logger.Level.FULL)
                .target(ElasticSearchService.class, host);
         }

        public interface ElasticSearchService {

           @RequestLine("POST /document/{id}")
            public ElasticPostResponse addInfo(@Param("id") Integer id, Resume resume);
         
           @RequestLine("GET /_search?q={body}")
            public ElasticGetResponse workingGetInfo(@Param("body") String body);

           @RequestLine("GET /_search?q=body:{body}")
           public ElasticGetResponse brokenGetInfo(@Param("body") String body);
    }
}


Creating it in another class.

    private ElasticSearchFactory.ElasticSearchService
            elasticSearchService = ElasticSearchFactory.elasticSearchService();

Then calling it like this:
    
    ElasticGetResponse elasticGetResponse = elasticSearchService.getInfo(query);

**Comment by adriancole** [comment] 2016-08-04 00:10
No obvious problem. I will have a look and get back by tomorrow

**Comment by jaylucas** [comment] 2016-08-04 01:18
Thanks for the help!!

**Comment by adriancole** [comment] 2016-08-04 18:43
This is a bug for sure. Not sure yet which of the various recent changes caused it.

```java
  interface Issue424 {
    @RequestLine("GET /_search?q=body:{body}")
    String get(@Param("body") String body);
  }

  @Test
  public void getDoesntImplyFormParams() throws Exception {
    List<MethodMetadata> mds = contract.parseAndValidatateMetadata(Issue424.class);
    assertThat(mds.get(0).formParams()).isEmpty();
  }
```

**Comment by adriancole** [comment] 2016-08-04 18:48
actually, I see what's going on.

We added support for partial-match on headers, and not on queries. Ex. the `{body}` part is a partial-match on the query param `q`.

**Comment by adriancole** [comment] 2016-08-04 18:57
https://github.com/OpenFeign/feign/pull/428

**Comment by jaylucas** [comment] 2016-08-05 01:46
This is great thank you

**Comment by adriancole** [comment] 2016-08-05 04:08
Sure sorry about the delay

**Comment by jaylucas** [comment] 2016-08-16 03:39
Sorry for the super late response. I was away of vacation.

But the update *almost works as intended:

    [ElasticSearchService#getResumes] ---> GET http://localhost:9200/_search?q=body%3A%7Bquery%7D HTTP/1.1
    [ElasticSearchService#getResumes] ---> END HTTP (0-byte body)
    [ElasticSearchService#getResumes] <--- HTTP/1.1 400 Bad Request (43ms)
    [ElasticSearchService#getResumes] content-length: 2199
    [ElasticSearchService#getResumes] content-type: application/json; charset=UTF-8
    [ElasticSearchService#getResumes] 
    [ElasticSearchService#getResumes] {"error":{"root_cause":   [{"type":"query_parsing_exception","reason":"Failed to parse query [body:{query}]","index":"1"},{"type":"query_parsing_exception","reason":"Failed to parse query [body:{query}]","index":"document"},{"type":"query_parsing_exception","reason":"Failed to parse query [body:{query}]","index":"test"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"1","node":"MWwTeNKxTfGi4QewR6zb9g","reason":{"type":"query_parsing_exception","reason":"Failed to parse query [body:{query}]","index":"1","caused_by":{"type":"parse_exception",

**Comment by adriancole** [comment] 2016-08-16 04:05
that doesn't look like almost works :) it looks like "doesn't work at all"!

sure you are on latest feign, right?

**Comment by jaylucas** [comment] 2016-08-16 04:08
https://mvnrepository.com/artifact/com.netflix.feign/feign-core/8.18.0

**Comment by adriancole** [comment] 2016-08-16 04:12
latest has the fix:

<dependency>
    <groupId>io.github.openfeign</groupId>
    <artifactId>feign-core</artifactId>
    <version>9.1.0</version>
</dependency>

**Comment by jaylucas** [comment] 2016-08-16 04:13
Yeah I tried this too:
https://mvnrepository.com/artifact/io.github.openfeign/feign-core/9.1.0

**Comment by jaylucas** [comment] 2016-08-16 04:17
So the actual log with 9.1.0 is:

    [ElasticSearchService#getResumes] ---> GET http://localhost:9200/_search?q=body%3A%7Bbody%7D HTTP/1.1
    [ElasticSearchService#getResumes] ---> END HTTP (0-byte body)
    [ElasticSearchService#getResumes] <--- HTTP/1.1 400 Bad Request (53ms)
    [ElasticSearchService#getResumes] content-length: 2190
    [ElasticSearchService#getResumes] content-type: application/json; charset=UTF-8
    [ElasticSearchService#getResumes] 
    [ElasticSearchService#getResumes] {"error":{"root_cause":[{"type":"query_parsing_exception","reason":"Failed to parse query [body:{body}]","index":"1"},{"type":"query_parsing_exception","reason":"Failed to parse query [body:{body}]","index":"document"},{"type":"query_parsing_exception","reason":"Failed to parse query [body:{body}]","index":"test"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"1","node":"MWwTeNKxTfGi4QewR6zb9g","reason":{"type":"query_parsing_exception","reason":"Failed to parse query [body:{body}]","index":"1","caused_by":{"type":"parse_exception","reason":"Cannot parse 'body:{body}': Encountered \" \"}\" \"} \"\" at line 1, column 10.\nWas expecting one of:\n    \"TO\" ...\n    <RANGE_QUOTED> ...\n    <RANGE_GOOP> ...\n    ","caused_by":{"type":"parse_exception","reason":"Encountered \" \"}\" \"} \"\" at line 1, column 10.\nWas expecting one of:\n    \"TO\" ...\n    <RANGE_QUOTED> ...\n    <RANGE_GOOP> ...\n    "}}}},{"shard":0,"index":"document","node":"MWwTeNKxTfGi4QewR6zb9g","reason":{"type":"query_parsing_exception","reason":"Failed to parse query [body:{body}]","index":"document","caused_by":{"type":"parse_exception","reason":"Cannot parse 'body:{body}': Encountered \" \"}\" \"} \"\" at line 1, column 10.\nWas expecting one of:\n    \"TO\" ...\n    <RANGE_QUOTED> ...\n    <RANGE_GOOP> ...\n    ","caused_by":{"type":"parse_exception","reason":"Encountered \" \"}\" \"} \"\" at line 1, column 10.\nWas expecting one of:\n    \"TO\" ...\n    <RANGE_QUOTED> ...\n    <RANGE_GOOP> ...\n    "}}}},{"shard":0,"index":"test","node":"MWwTeNKxTfGi4QewR6zb9g","reason":{"type":"query_parsing_exception","reason":"Failed to parse query [body:{body}]","index":"test","caused_by":{"type":"parse_exception","reason":"Cannot parse 'body:{body}': Encountered \" \"}\" \"} \"\" at line 1, column 10.\nWas expecting one of:\n    \"TO\" ...\n    <RANGE_QUOTED> ...\n    <RANGE_GOOP> ...\n    ","caused_by":{"type":"parse_exception","reason":"Encountered \" \"}\" \"} \"\" at line 1, column 10.\nWas expecting one of:\n    \"TO\" ...\n    <RANGE_QUOTED> ...\n    <RANGE_GOOP> ...\n    "}}}}]},"status":400}
[ElasticSearchService#getResumes] <--- END HTTP (2190-byte body)

**Comment by adriancole** [comment] 2016-08-16 05:18
sheesh I think you're right. there is another place we need to change.

**Comment by adriancole** [comment] 2016-08-16 05:25
Failing test:

```java
  @Test
  public void resolveTemplateWithParameterizedSubstringQueryValue() {
    RequestTemplate template = new RequestTemplate().method("GET")
        .append("_search").query("q", "body:{body}");

    template.resolve(mapOf("body", "text"));

    assertThat(template)
        .hasQueries(entry("q", asList("body:text")));
  }
```

**Comment by adriancole** [comment] 2016-08-16 15:17
@jaylucas might be a couple days to fix.. here's a workaround that would work if you have only one input to the "q" parameter:

```
    @RequestLine("GET /_search?q={q}")
    public ElasticGetResponse getResumes(@Param(value = "q", expander = PrefixBodyExpander.class) String body);

  static final class PrefixBodyExpander implements Param.Expander {
    @Override
    public String expand(Object value) {
      return "body:" + value;
    }
  }
```

**Comment by jaylucas** [comment] 2016-08-16 15:27
Yeah I figured. I have been doing that while this issue is being resolved. The problem with that is when dealing with ids. let say:

    /_search?q=1

This searches all occurrences of 1 which can be many more times then the unique id im looking for

    /_search?q=id:1

Grabs the 1 value Im looking for

**Comment by adriancole** [comment] 2016-08-16 15:31
id:1 would still work with the janky workaround :) Anyway glad you have a workaround.. should have this sorted in a few days.

```
 static final class PrefixIdExpander implements Param.Expander {
    @Override
    public String expand(Object value) {
      return "id:" + value;
    }
  }
```

**Comment by jaylucas** [comment] 2016-08-16 15:34
Thank you 👍

**Comment by DevAwas** [comment] 2017-10-09 10:47
Is this sorted yet? I am unable to run my client like:
	@Headers(HttpHeaders.CONTENT_TYPE + ":" + MediaType.APPLICATION_JSON_VALUE)
	@RequestLine("GET /search?query:{query}")
	Map<?,?> getProductDetails(@Param(value = "query") String query);

I run into NPE at Caused by: java.lang.NullPointerException: null
	at feign.Contract$Default.searchMapValuesContainsSubstring(Contract.java:291)
	at feign.Contract$Default.processAnnotationsOnParameter(Contract.java:264)
	at feign.Contract$BaseContract.parseAndValidateMetadata(Contract.java:107)
	at feign.Contract$BaseContract.parseAndValidatateMetadata(Contract.java:64)
	at feign.ReflectiveFeign$ParseHandlersByName.apply(ReflectiveFeign.java:146)
	at feign.ReflectiveFeign.newInstance(ReflectiveFeign.java:53)
	at feign.Feign$Builder.target(Feign.java:218)
	at org.springframework.cloud.netflix.feign.HystrixTargeter.target(HystrixTargeter.java:39)

**Comment by DevAwas** [comment] 2017-10-09 10:59
ignore my query, i was passing incorrectly, sorry!

**Comment by slepasteur** [comment] 2018-01-03 09:23
Any new on that? I try calling an API with a request looking like ".../test?param=value={v}" but the "{v}" is not replaced (using version 9.5.1).
```
@RequestLine ("GET /test?param=value={v}")
void test(@Param ("v") String v);
```

**Comment by kdavisk6** [comment] 2019-12-27 21:54
@slepasteur 
Your RequestLine is incorrect.  You will need to fix the query string before the substitution will work:

```java 
@RequestLine ("GET /test?param=&value={v}")
void test(@Param ("v") String v);
```

Second, this issue should be fixed for most cases outlined.  I'm going to close this issue.  Please create a new issue, including a test case if you can, if you continue to have trouble.

**Closed by kdavisk6** 2019-12-27 21:54 UTC
Labels: bug
