### ISSUE TITLE
Ribbon tests fail

### ISSUE THREAD

**Issue by johnament** [OpenFeign/feign#501] opened 2016-12-04 13:32 UTC
I'm not sure if this is a local issue or something just out there.  Building master results in these test failures in Ribbon:

```
Failed tests:   ribbonRetryConfigurationOnMultipleServers(feign.ribbon.RibbonClientTest): expected:<1> but was:<2>
  ribbonRetryConfigurationOnSameServer(feign.ribbon.RibbonClientTest)
  ioExceptionFailsAfterTooManyFailures(feign.ribbon.RibbonClientTest): No exception thrown
```

For what its worth, I do see random failures using Ribbon locally as well.  I'm not sure if its all related.  I've attached the full failure report, mostly to keep the ticket brief.  I'll also point out - my PR failed on this error and my local fails even without that PR on it so.... any help would be greatly appreciated 

[test-failure.txt](https://github.com/OpenFeign/feign/files/629542/test-failure.txt)

**Comment by kdavisk6** [comment] 2018-07-26 01:19
Duplicate of #513

**Closed by kdavisk6** 2018-07-26 01:19 UTC
Labels: duplicate
