### ISSUE TITLE
[version10.x]can't work with a json param,but version9.x is ok.

### ISSUE THREAD

**Issue by yuli13244** [OpenFeign/feign#922] opened 2019-03-16 14:37 UTC
example:
```java
public class GitHubExample {

  interface GitHub {

    @RequestLine(value = "GET /s?word={wd}")
    String test(@Param("wd") String query);

    static GitHub connect() {
      return Feign.builder()
              .decoder(new StringDecoder())
              .logger(new Logger.ErrorLogger())
              .logLevel(Logger.Level.BASIC)
              .target(GitHub.class, "http://localhost:8080");
    }
  }

  public static void main(String... args) {
    GitHub github = GitHub.connect();
    String test = github.test("{\"name\":\"feign\",\"version\": \"10\"}");
    System.out.println(test);
  }
}
```

after run the code above.the console print the target url:
```shell
[GitHub#test] ---> GET http://localhost:8080/s?word=%7B%22name%22:%22feign%22&word=%22version%22:%20%2210%22%7D HTTP/1.1
```
the param "word" expand 2 times.

**Comment by kdavisk6** [comment] 2019-03-17 18:51
@yuli13244 

Thank you for brining this to our attention.  My first guess is the comma `,` in the `word` parameter is throwing off our collection encoding.  I'll take a look when I can.  In the meantime, one potential workaround is to encode the value yourself and set the `encoded` property of the `@Param` annotation to `true`.  This will by pass any internal encoding and processing.

**Comment by kdavisk6** [comment] 2019-04-10 12:13
Duplicate of #924 and #928

**Closed by kdavisk6** 2019-04-10 12:13 UTC
Labels: bug
