### ISSUE TITLE
Getting java.util.regex.PatternSyntaxException: Illegal repetition whenever I am trying to pass nested json string in my request header

### ISSUE THREAD

**Issue by RiddhiKhatri** [OpenFeign/feign#1598] opened 2022-03-22 04:43 UTC
I am getting "Illegal repetition\r\n{ " Exception when I am trying to pass nested JSON Object as the request header. If it is single JSON object it works fine. Is there any way I could add Nested JSON as the Request Header.

**Comment by Shapoval1van** [comment] 2022-04-18 17:47
I got a same Issue, do you know how to fix it?

**Comment by rage-shadowman** [comment] 2022-04-19 19:53
@RiddhiKhatri and @Shapoval1van: if you're asking a question, stackoverflow might be better. If you are reporting a bug, then a reproducible example would help.

**Comment by kdavisk6** [comment] 2022-10-07 20:59
Please provide a [minimal reproduceable example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates your issue along with the expected behavior and actual behavior observed.

**Comment by JKomoroski** [comment] 2022-10-22 01:45
Hard to say with certainty without more detail, but this looks like another json header issue fixed in master at HEAD now but not yet released. Related to the fixes that came in for https://github.com/OpenFeign/feign/issues/1464

I believe this can be closed @kdavisk6

**Closed** 2024-09-13 02:33 UTC
Labels: needs info
