### ISSUE TITLE
@QueryMap doesn't work with inheritance

### ISSUE THREAD

**Issue by StasKolodyuk** [OpenFeign/feign#927] opened 2019-03-26 13:12 UTC
Hi,

I've raised an [issue](https://github.com/spring-cloud/spring-cloud-openfeign/issues/168) in spring-cloud-openfeign project related to @SpringQueryMap not working with inheritance.

However, seems like the root cause is in `FieldQueryMapEncoder` of feign-core https://github.com/OpenFeign/feign/blob/10a4eadf4f3312573354672c9f5f9e322a30e5c5/core/src/main/java/feign/querymap/FieldQueryMapEncoder.java#L69-L75

It uses `type.getDeclaredFields()` which returns only fields of a class without inherited fields.

Thanks

**Comment by kdavisk6** [comment] 2019-03-26 16:49
@StasKolodyuk 

Thanks for bringing this up.  If I recall, this is by design, as Feign's support for bean properties is intentionally simple.  This would be an enhancement for us.  So I've marked this issue as such.  If you would like this feature, please feel free to open a PR.

**Comment by FatTigerWang** [comment] 2019-03-27 01:28
> @StasKolodyuk
> 
> 谢谢你提出这个问题。如果我记得，这是设计，因为Feign对bean属性的支持是故意简单的。这对我们来说是一种增强。所以我已经标记了这个问题。如果您想要此功能，请随时打开公关。

support inheritance is very important

**Comment by kdavisk6** [comment] 2019-05-28 15:14
Resolved via #960

**Closed by kdavisk6** 2019-05-28 15:14 UTC
Labels: enhancement, help wanted
