### ISSUE TITLE
FeignRetryableException When Service is down

### ISSUE THREAD

**Issue by PrateekRavilla** [OpenFeign/feign#776] opened 2018-09-02 01:17 UTC
Hi Team,
 
We had an issue with Feign Retryable Exception. We have 3 layers A, B and C with Feign. A is making a call to B, and B is making call to C. When C is down, we are handling Retryable Exception in B and returning response to A. But A is not able to get that response and A is getting Retryable exception even it is handled in B layer.  We are able to see handled response in B layer. This issue is coming with multiple layer calls. We have a custom class FeignErrorDecoder which implements ErrorDecoder. Retryable Exception is also not going to the custom error decoder.  I appreciate the help in this issue. Thank you.

**Comment by kdavisk6** [comment] 2018-09-09 17:04
Can you provide some sample code for us to review?  I'm having a difficult time following what the issue is and what the expected behavior should be.

**Comment by PrateekRavilla** [comment] 2018-09-09 19:02
Sorry,i can't provide any kind of codebase ,as it's kind of confidential.My only concern is even though i catch the feign retryable exception in one layer why is not carried forward to next layer

**Comment by kdavisk6** [comment] 2018-09-09 22:41
Would you be able to create a simple test case that doesn't violate any agreements?  

`RetryableExceptions` are typically created when an `IOException` occurs during a request or directly from an `ErrorDecoder`. 

`RetryableExceptions` are *not* passed to `ErrorDecoders`.  `ErrorDecoders` are meant to process `Responses` with 4xx and 5xx response codes, with the notable exception of a 503.  This means that you will not be able to handle `RetryableExceptions` in an `ErrorDecoder` because the `RetryableException` is thrown before the `Response` can be handled, if a 503 status is returned or an `IOException` was triggered.

You may need to rework your error handling with this in mind.  You may also want to consider using `Hystrix` instead.  `Hystrix` provides more robust retry and fallback handling than core feign.  Take a look at `HystrixFeign` for how to use `Hystrix` with `Feign`

**Comment by kdavisk6** [comment] 2019-04-18 12:35
For those who come across this, the Error Decoder documentation outlines how to trigger your own versions of a `RetryableException`.  However, chaining retries, as suggested here, are something that is out of scope for feign itself.  Our suggestion is to combine `feign` with `hystrix` or `resilience4j` or any other Circuit Breaker/Bulkhead library to manage the service fallbacks.

**Closed by kdavisk6** 2019-04-18 12:35 UTC
Labels: documentation, question
