### ISSUE TITLE
Why feign performs urlencode twice on the query parameter values?

### ISSUE THREAD

**Issue by ryeyao** [OpenFeign/feign#483] opened 2016-10-29 11:06 UTC
Feign encodes a query string twice that _:_ finally becomes _%253A_ and the correct result should be _%3A_.

First encoding happens when creating a `RequestTemplate` ([ReflectiveFeign.java:213](https://github.com/OpenFeign/feign/blob/master/core/src/main/java/feign/ReflectiveFeign.java#L213))
`RequestTemplate template = resolve(argv, mutable, varBuilder);`

Second encoding happens when constructing a `Request` ([SynchronousMethodHandler.java:88](https://github.com/OpenFeign/feign/blob/master/core/src/main/java/feign/SynchronousMethodHandler.java#L88))
`Request request = targetRequest(template);`

Though one of the RequestTemplate's query() methods accepts a boolean parameter to determine whether to encode the query parameter values, the default value of this boolean is false and there is no way to change its value.

Finally, I have to write a `RequestInterceptor` to decode the query parameter values between the two encodings. 

Why would feign do two encodings on query parameter values? Is it a bug or did I miss something?

**Comment by kgym** [comment] 2017-03-22 08:03
hi, @ryeyao , I encounter that problem too. But I don't success to modify the query part. Can you share me a demo code? Thx very much!

**Comment by qaohao** [comment] 2017-03-29 09:05
I encounter the problem yet. @ryeyao I'm sure it is a bug of feign. I have read the source code of feign:8.18.0,  once u request url with paramters by get method, and set the more paramters by @QueryMap, it will  encode parameter twice.

see code snippet of Feign **RequestTemplate.java**, there is the bug.
```
private StringBuilder pullAnyQueriesOutOfUrl(StringBuilder url) {
        int queryIndex = url.indexOf("?");
        if(queryIndex != -1) {
            String queryLine = url.substring(queryIndex + 1);
            Map firstQueries = parseAndDecodeQueries(queryLine);
            if(!this.queries.isEmpty()) {
                firstQueries.putAll(this.queries);
                this.queries.clear();
            }

            Iterator var5 = firstQueries.keySet().iterator();

            while(var5.hasNext()) {
                String key = (String)var5.next();
                Collection values = (Collection)firstQueries.get(key);
                if(this.allValuesAreNull(values)) {
                    this.queries.put(urlEncode(key), values);
                } else {
                    this.query(key, (Iterable)values);
                }
            }

            return new StringBuilder(url.substring(0, queryIndex));
        } else {
            return url;
        }
    }
```

**Comment by ryeyao** [comment] 2017-03-30 12:08
@kgym here is my quick workaround (ugly but works)：

```
@Component
public class FeignMonitorRequestInterceptor implements RequestInterceptor {
    private static String urlDecode(String arg) {
        try {
            return URLDecoder.decode(arg, Util.UTF_8.name());
        } catch (UnsupportedEncodingException e) {
            throw new RuntimeException(e);
        }
    }

    @Override
    public void apply(RequestTemplate template) {
        
        for (String key : template.queries().keySet()) {
            Collection<String> values = template.queries().get(key);
            if (allValuesAreNull(values)) {
                continue;
            } else {
                Collection<String> encodedValues = new ArrayList<String>();
                for (String value : values) {
                    encodedValues.add(urlDecode(value));
                }
                template.query(true, key, encodedValues);
            }
        }
    }

    private boolean allValuesAreNull(Collection<String> values) {
        if (values == null || values.isEmpty()) {
            return true;
        }
        for (String val : values) {
            if (val != null) {
                return false;
            }
        }
        return true;
    }
}
```

**Comment by albertjose** [comment] 2018-03-26 15:46
Same here, thanks for that @ryeyao

**Comment by kdavisk6** [comment] 2018-03-26 15:49
Yeah, I think that in some cases the url processing is delegated to the `Client`, which we found in #637 and with your research, the `RequestTemplate` . If you think you have time, can you take a look and maybe submit a PR fix?

**Comment by albertjose** [comment] 2018-03-26 16:58
I'll try take a time to do that :)

**Comment by kdavisk6** [comment] 2018-07-26 01:23
Duplicate of #662

**Closed by kdavisk6** 2018-07-26 01:23 UTC
