### ISSUE TITLE
comma vs repeated name for collection query parameter

### ISSUE THREAD

**Issue by pennstatephil** [OpenFeign/feign#588] opened 2017-08-23 22:17 UTC
In support of #543 - if a request is made with many values, the max limit could be hit much faster by repetition of a query parameter vs comma-separated. e.g. ?id=1&id=2&id=3 vs ?id=1,2,3

**Comment by spencergibb** [comment] 2017-08-23 22:21
repeated query params is part of the spec, a comma separated list isn't.

**Comment by pennstatephil** [comment] 2017-08-23 22:23
not saying it isn't, but the option to change the default behavior without implementing a request interceptor (which was the resolution for a similar request in https://github.com/spring-cloud/spring-cloud-netflix/issues/1634) would be great.

**Comment by rage-shadowman** [comment] 2018-03-24 03:48
It's not pretty, but you could do this if you wrap the iterable in some sort of `CsvObject` (which is not itself an iterable, but has a `toString` method that just joins your iterable into a CSV string to return).

You may also be able to modify the code to add an additional optional parameter to the `@Param` annotation that modifies the behavior of the `ReflectiveFeign.BuildTemplateByResolvingArgs.expandIterable` method and submit a pull request.

I'd personally like to see the CSV vs Multiple Query Params behavior be configurable and just defaulted to the current behavior.

**Comment by rage-shadowman** [comment] 2018-03-24 03:53
This looks like a duplicate of #542

**Comment by pennstatephil** [comment] 2018-03-24 04:02
#543 was opened to address #542, so I'd agree.

**Comment by rage-shadowman** [comment] 2018-03-24 04:14
Then what is it you are asking for (other than allowing CSV expansion of iterables in request parameters -- which is what #542 and #543 are about)?

**Comment by pennstatephil** [comment] 2018-03-24 04:17
> since the merge request is waiting for votes, I am adding my vote.

**Comment by rage-shadowman** [comment] 2018-03-24 04:25
I added my thumbs-up to that issue. I hope they see that as a +1 vote, as I do want to see that added.

**Closed** 2018-07-26 00:59 UTC
Labels: duplicate
