### ISSUE TITLE
Empty body on HTTP error response

### ISSUE THREAD

**Issue by stromnet** [OpenFeign/feign#260] opened 2015-08-31 15:30 UTC
I had a problem where the response body would come up empty, when the server responded with 401:

```
2015-08-31 17:11:01.168 [MyInterface#myMethod] <--- HTTP/1.1 401 Unauthorized (12ms)
2015-08-31 17:11:01.169 [MyInterface#myMethod] Date: Mon, 31 Aug 2015 15:11:01 GMT
2015-08-31 17:11:01.169  [MyInterface#myMethod] Content-Length: 71
2015-08-31 17:11:01.170  [MyInterface#myMethod] Content-Type: application/json
2015-08-31 17:11:01.170  [MyInterface#myMethod] <--- END HTTP (0-byte body)

```

As indicated by content-length header, the body should be 71 bytes, and it is (verified with tcpdump).
The empty body caused a NPE when the ErrorDecoder had nothing to decode and returned null, which SynchronousMethodHandler then tried to throw (line 121).

During previous testing, with 200 OK it worked fine, if I recall correct.

This was with the Default client. Using OkHttpClient instead, the issue disappeared.

**Comment by adriancole** [comment] 2015-09-03 23:39
Thanks for the report. Are you able to reproduce this in a MockWebServer
test? (saying no is acceptable :P )

**Comment by stromnet** [comment] 2015-09-04 07:42
Actually, no. I tried the following in BaseApiTest:

```
  @Test
  public void handlesErrorBody() throws InterruptedException {
    server.enqueue(new MockResponse().setResponseCode(401).setBody("foo"));

    String baseUrl = server.getUrl("/default").toString();

	 try {
		Feign.builder()
			.logLevel(Logger.Level.FULL)
			.client(new Client.Default(null, null))
			 .errorDecoder(new ErrorDecoder.Default())
			 .target(MyApi.class, baseUrl).get("foo");
		fail();
	 }catch(FeignException ex) {
		 assertThat(ex.getMessage())
			 .isEqualTo("status 401 reading MyApi#get(String); content:\nfoo");
	 }
  }
```

And this passes fine, the response gets through without a problem.. Weird! When I had the issue, the remote end was a Jersey-based server. As I mentioned, the tcpdump on localhost showed the actual bytes being sent.. The only difference was that I was using a JacksonDecoder, but I tried that as well and couldn't reproduce the error.
Even tried targeting the test towards the Jersey server, and it still worked. Could this have something to do with the runtime environment in which the test/HttpURLConnection is running in? Not sure if there are any customizations in the faulty environment, it's a spring boot environment so it might set all sorts of weird things (if even possible).

Sidenote: even though I specify Full logging level (and forcing the Logger-level on feign.Logger to All), I don't see the http dump as I did in my original code (which uses the Slf4jLogger).. adding a System.out.println line in the log method did show proper output though.

**Comment by stromnet** [comment] 2015-09-04 07:47
Tested with both v8.7.1 and master.

**Comment by adriancole** [comment] 2015-09-08 12:38
I wonder if something is overriding the URLStreamHandlerFactory like how we do in okhttp:

```java
URL.setURLStreamHandlerFactory(new OkUrlFactory(okHttpClient));
```

This would manifest as a different type of object (like in a different package) for HttpURLConnection.

**Comment by emilnkrastev** [comment] 2016-05-17 09:11
This is not a problem in feign - this is how HttpURLConnection works. Currently in the feign.Default client there is a streaming mode enabled. You can see in the sun.net.www.protocol.http.HttpURLConnection following lines of code : 
`if (respCode == HTTP_UNAUTHORIZED) { 
		if (streaming()) {
                     disconnectInternal();
                    throw new HttpRetryException (RETRY_MSG2, HTTP_UNAUTHORIZED);
        }`

So if the streaming is enabled and you have 401 HTTP response code you will get empty errorStream, because there is no initialization. The feign client will try to get the errorStream as a body because there is a check 
`      if (status >= 400) {
        stream = connection.getErrorStream();
      } else {
        stream = connection.getInputStream();
      }
      `

Currently I removed the streaming in the cient.
`      connection.setFixedLengthStreamingMode(contentLength);
       connection.setChunkedStreamingMode(8196);`

**Comment by vincent-ren** [comment] 2017-03-27 13:36
In the spring cloud feign, how can I get the error message when http code is 401?

**Comment by frankskywalker** [comment] 2017-06-13 14:52
@vincent-ren 
using okhttp3 could get you the body.

**Comment by vincent-ren** [comment] 2017-06-14 09:05
@frankskywalker thank you for you answer my question, I have resloved this problem, do not using the default client, using feign-okhttp or feign-httpclient all is ok.

**Comment by kdavisk6** [comment] 2018-09-14 14:58
This feels like a bug to me.  We may need more `null` checking before blindly reading the error stream.

**Comment by ColtonPaysafe** [comment] 2018-11-05 20:59
This is caused by https://github.com/OpenFeign/feign/blame/master/core/src/main/java/feign/Client.java#L85...  Setting `allowUserInteraction` to false immediately closes the stream and causes `getErrorStream`.

See also: https://stackoverflow.com/a/44423631/8651856

**Comment by ColtonPaysafe** [comment] 2018-11-05 21:02
My recommendation would be to release a minor version with `Request$Options` containing a `allowUserInteraction` boolean (default to false).  In the next major release, change the default to true.

**Comment by 344310362** [comment] 2018-12-06 09:29
这个修复啥时候发布，怎么就把参数定死了。

**Comment by rage-shadowman** [comment] 2018-12-06 20:55
@344310362 english comments are more likely to be understood by most of the people following this project.

Google translate isn't very good here as it turns that into:
> When this fix is released, how can I set the parameters to death?

**Comment by kdavisk6** [comment] 2018-12-12 18:35
There issue is marked as help-wanted, indicating that if someone wants to take a look and try to fix this, please do and raise a PR.

**Comment by kdavisk6** [comment] 2019-12-27 16:41
After looking into this recently, I can see that this behavior is specific to JDK versions prior to 1.8.  I'm going to close this issue and recommend that user's test with JDK 1.8.

**Closed by kdavisk6** 2019-12-27 16:41 UTC
Labels: bug, help wanted

**Comment by murkfeel** [comment] 2020-02-04 12:09
Hey guys. I had this problem and set the OkHttp to Openfeign and fixed.

In order to know how can use from OkHttp in Openfeign refer to [here](https://www.baeldung.com/spring-cloud-openfeign)

**Comment by verils** [comment] 2020-02-28 10:42
Unfortunately this 'feature' has remained to JDK 11. I just tested

**Comment by nada-gamal** [comment] 2021-03-10 16:23
Did anybody had a workaround to resolve this issue? It is existing I am using JDK 11 and Openfeign 2.2.6. I have tried with other clients other than the default Okhttp and Apache HttpClient and still getting empty response body with 401 error response.

**Comment by minhnguyenvan95** [comment] 2022-10-12 08:00
> Did anybody had a workaround to resolve this issue? It is existing I am using JDK 11 and Openfeign 2.2.6. I have tried with other clients other than the default Okhttp and Apache HttpClient and still getting empty response body with 401 error response.

Same too me , response code = 401 the response body return null, JDK 17, Feign 3.1.4

**Comment by ariady-putra** [comment] 2023-07-06 03:46
2023 and this is still a thing. Can't the team test their own product?

**Comment by velo** [comment] 2023-07-06 04:34
Sorry to hear all your effort, contributions and financial incentives
didn't pay out.

Happy to refund you

**Comment by velo** [comment] 2023-07-06 04:36
> > Did anybody had a workaround to resolve this issue? It is existing I am using JDK 11 and Openfeign 2.2.6. I have tried with other clients other than the default Okhttp and Apache HttpClient and still getting empty response body with 401 error response.
> 
> Same too me , response code = 401 the response body return null, JDK 17, Feign 3.1.4

Feign 3? That is 10 releases old. Is like trying to run spring 1 with jdk 17.

**Comment by andreaippo** [comment] 2024-04-12 10:49
I can confirm that using the okhttp client the problem disappears (https://github.com/OpenFeign/feign/blob/6408e3ef9664ee6594c12d9e3c2cc91fd29119d0/okhttp/src/main/java/feign/okhttp/OkHttpClient.java)

To add it to our project we had to:

add the pom dependency:

```
<dependency>
<groupId>io.github.openfeign</groupId>
<artifactId>feign-okhttp</artifactId>
</dependency>
```

And in the feign config bean, make sure to init your Feign with sth like:

`Feign.builder().client(new feign.okhttp.OkHttpClient())...;`
