### ISSUE TITLE
spring cloud issue

### ISSUE THREAD

**Issue by qq86865810** [OpenFeign/feign#609] opened 2017-11-30 03:09 UTC
In spring cloud project
I use feign with hystrix
but when the microserver provider had the error , the feign cannot find the fallback method
so i test the code
this is the sample test code
UserFeignClient.class
@FeignClient(name = "yyf-provider-user", fallback = UserFeignClientImpl.class)
public interface UserFeignClient {

    @RequestMapping(value = "/{id}", method = RequestMethod.GET)
    public User findById(@PathVariable("id") Long id);

}
UserFeignClientImpl.class
@Component
public class UserFeignClientImpl implements UserFeignClient {
    @Override
    public User findById(Long id) {
        User user = new User();
        user.setId(-1L);
        user.setUserName("default user");
        return user;
    }
}
in the spring cloud Camden version , the feign can find the fallback method 
but the newer version cannot find the fallback method such as dalston 
i check the doc bewteen camden and dalston
cannot find the diffrent

**Comment by spencergibb** [comment] 2017-11-30 03:13
Duplicate of https://github.com/spring-cloud/spring-cloud-netflix/issues/2486

**Closed by spencergibb** 2017-11-30 03:13 UTC
