### ISSUE TITLE
Plus sign is not properly encoded within query parameter

### ISSUE THREAD

**Issue by vilbara** [OpenFeign/feign#881] opened 2019-01-24 15:52 UTC
Feign version: 10.1.0

If PLUS character ("+") is passed within query parameter to feign-generated client, it arrives as SPACE on the target server.

```
FooApi {
    @RequestLine("GET` /foo/?q={q}")
    List<Foo> getFoo(@Param("q") String q);
}

fooApi.getFoo("a+b");
// -> results in "a b" on the server.
```

**Comment by kdavisk6** [comment] 2019-01-24 16:03
Duplicate of #879

**Closed by kdavisk6** 2019-01-24 16:03 UTC
