### ISSUE TITLE
POST  uploadFile, has 411 

### ISSUE THREAD

**Issue by YLIU356Volvocars** [OpenFeign/feign#2492] opened 2024-07-31 07:06 UTC
I have a request from the client to the service ,but occurred 411 ,below messages:
feign.FeignException$FeignClientException: status 411 reading FileServiceClient#handleFileUpload(MultipartFile)
	at feign.FeignException.clientErrorStatus(FeignException.java:181)
	at feign.FeignException.errorStatus(FeignException.java:141)
	at feign.FeignException.errorStatus(FeignException.java:133)
	at feign.codec.ErrorDecoder$Default.decode(ErrorDecoder.java:92)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:151)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:80)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
	at com.sun.proxy.$Proxy209.handleFileUpload(Unknown Source)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

I need help.  

  client:
![image](https://github.com/user-attachments/assets/0a3c8a87-3b62-4942-b2c0-5000fbe05450)

service:
![image](https://github.com/user-attachments/assets/49fbf052-fc1e-4871-82b9-e4f1a4c0b35f)

**Comment by kdavisk6** [comment] 2024-09-11 00:30
Duplicate of #2493

**Closed by kdavisk6** 2024-09-11 00:30 UTC
