### ISSUE TITLE
Null values when user expect Object in Response

### ISSUE THREAD

**Issue by hadson172** [OpenFeign/feign#1013] opened 2019-07-19 13:50 UTC
When user expect Object with the body of response feign shouldn't return null because this leads to NullPointerException and failure. It should throw FeignException instead:

```
interface People {
    @RequestLine(...)
    Person findPersonById(...) // FeignException instead of null value
}

```
When user expect that body could be empty Feign should return empty optional instead of null value:

```
interface People {
    @RequestLine(...){
    Optional<Person> findPersonById(...) // Optional.empty instead of null value
}

```

**Comment by kdavisk6** [comment] 2019-07-19 14:43
@hadson172 

This behavior is driven by the `Decoder`.  The default `Decoder` does not support `null` responses, it throws a `FeignException` by design.  You will need to use a different `Decoder` or create a custom `Decoder` for your business logic.

In the `Optional` use case, the built in `OptionalDecoder` delegates to the original `Decoder` and therefore, has the same responsibilities.

I recommend that you review our [Decoder documentation](https://github.com/OpenFeign/feign#decoders) again and consider creating your own `Decoder` with the behavior you require.  Here is a quick sample that may get you started:

```java
public class PersonDecoder implements Decoder {
    public Object decode(Response response, Type type) {
        if (response.body() == null) {
            return null;
        }
        /* continue to process the response */
    }
}
```

**Comment by hadson172** [comment] 2019-07-19 14:56
@kdavisk6 Didn't saw OptionalDecoder thank's for that.

As far as I can see in source code for JacksonDecoder or DefaultDecoder when the body is null or empty string and I expect object then the result is null.  So this work as design ? If so, why such decision was made? 

In my opinion it isn't normal situation when user expect something and when gets nothing there is silent failure. And instead of FeignException what i am getting is Null Pointer Exception which is the worst one. Don't you agree?

**Comment by kdavisk6** [comment] 2019-07-19 15:07
From our perspective, it's not possible for us to know what a user expects, there are simply too many use cases to consider.  For example, in your situation, you may expect `null`, yet in someone else's situation, an `Exception` is expected.  So we delegate this decision to the `Decoder`, which, as you've discovered, handles only the most straightforward situations and gives up on all others.

We aim to simplify the steps of the request processing but not take on the business logic of doing so.  We delegate that to you through our `Client`, `Encoder`, `Decoder`, `Logger`, and `ErrorDecoder` interface extensions.  It's unrealistic to expect this, or any library of this type, to understand your needs and provide support for every situation.  

With that said, if we are inconsistent in our approach across the built-in components, we should correct that.

**Comment by hadson172** [comment] 2019-07-19 15:46
Understood.  Let me describe what i was trying to do.

So, at first i was trying to get deserialized object, with data like http headers and status code from interface something like `ResponseEntity<Person>` from spring. So i started to search for solution and come up with issue opened here that this won't be implemented because of pluggable components. So i thought thats good i will write my own decoder.

I created class `MyCustomResponse<T>` which deserialize Response body to `T` and put there headers and status code. Image my suprise when i put everthing in montion and suddently i am getting FeignException with status code 500. 

So, feign allows user to put custom decoder and still decodes his response and throws exception if  
200 <= httpcode <300. Damn i want my `MyCustomResponse` with status code 500 and i cannot get it.

Then i tought nevermind i will use default decoder and jackson decoder and handle exception using my own ErrorDecoder. Suddenly when i run my code i got null pointer exception.

Where is inconsistency here?
In one place feign validates whether Type is not of type `Response.class` and if so feign decodes error code for me which what i don't want to, since i provided my own decoder for all responses not only happy path responses.

If this would be consistent probably you should check wheather Type is not of type` Response.class `and then throw exception instead of returning null. But you don't want make here this check because of flexability so why in example above this check was made? Thanks

**Comment by kdavisk6** [comment] 2019-11-15 21:42
@hadson172 

Apologies for taking so long to respond.  I think I can see where you may be getting confused.  Feign's usage model *wants* you to build business object that represent the HTTP Request and Response details.  When you bypass that and rely on `Response` information some of the built in conventions don't make sense.  This is what I think has happened in your case.  First, a little background.

Feign's response handling relies on two components, `Decoder` and `ErrorDecoder`.  If a HTTP Request responds with a status code within of the successful (2xx) range, processing will be delegated to the registered `Decoder`.  In all other cases, processing will be delegated to the `ErrorDecoder`.  You've observed this behavior.  This is not what you expect because you want to handle **every** response in your `Decoder`, which is not intended, by design.  Let me try to explain our intentions with a simple, yet contrived example.

Let's say we have a very simple CMS system used to power our company's Marketing Site.  It exposes a single simple endpoint `/posts` that provide all of the posts in our sites feed.  Using Feign, the interface could look like this:

```java
interface MarketingContentService {
   @RequestLine("GET /posts")
   Posts getPosts() throws ContentServiceException;
}
```

The contract from this API also states that additional information regarding caching and the like will be included as Headers in the response.  To support this we will need a custom `Decoder` to populate that information in our `Posts` object called `PostsDecoder`.  We also need to handle situations when we can't get the latest posts and return our cached `Posts`.  For that we will also need an `ErrorDecoder`.  We can configure our `Feign` instance this way:

```java
MarketingContentService marketingContentService = 
   Feign.builder()
      .decoder(new PostsDecoder())
      .errorDecoder(new PostsErrorHandler())
      .target(MarketingContentService.class, "https://marketing.cms");
```

Our `Decoder` is responsible for managing successful responses.  For that we'll read the response and build our object:

```java
public class PostsDecoder implements Decoder {
   
   public PostsDecoder() {
      super()
   }

   public Object decode(Response response, Type type) {
      Posts posts = new Posts();

      // read the cache information from the header.
      posts.expireOn(response.getHeader("Cache-Control"));

      // read the posts
      posts.append(reponse.getBody());
      return posts;
   }
}
```

Next, we need to handle when the service is down or any other error in our `ErrorDecoder`.  This will be called for any unsuccessful responses `3xx -> 5xx`.

```java
public class PostsErrorHandler implements ErrorDecoder {
 
   public PostsErrorHandler() {
      super();
   }

   public Exception decode(String methodKey, Response response) {
      // we want to retry if we get a time out
      int status = response.getStatus();
      if (504 == status) {
         // retry
         throw new RetryableException(...);
      }

      // client errors should fail using our business exceptions
      throw new ContentServiceException(...); 
   }
}
```

With our logic in place we can now use our `MarketingContentService` and abstract the underlying HTTP communication away. 

```java
public class MarketingSite {
   private MarketingContentService marketingContentService;
   private PostsCache postCache;

   public MarketingSite() {
      this.postCache = new PostsCache();
      this.marketingContentService = 
         Feign.builder()
            .decoder(new PostsDecoder())
            .errorDecoder(new PostsErrorHandler())
            .target(MarketingContentService.class, "https://marketing.cms");
   }

   public Model renderHomePage() {
      Model pageModel = new Model();
      try {
         Posts posts = this.marketingContentService.getPosts();
         this.postCache.cache(posts);
         pageModel.put("posts", posts);
         return model;
      } catch (ContentServiceException ex) {
         // handle the error appropriately
         if (this.postCache.hasPosts()) {
            pageModel.put("posts", this.postCache.posts());
         } else {
            pageModel.put("error", new Error("Sorry, no posts today"));
         }
         return model;
      }
   }
}
```

I know this is long winded, but I wanted to give you a clear demonstration of how Feign is intended to be used.  Bypassing these abstractions and using the lower level constructs should be avoided except in the most advanced cases where the abstractions get in the way.

If you feel your use case is advanced or that you do not see a way to use the abstractions to get you there, I'm more than happy to work with you and see if there is a way to achieve what you want before resorting to `Response` handling.  What do you think?

**Closed** 2020-12-29 19:40 UTC
Labels: feedback provided, question
