### ISSUE TITLE
Issue on QueryMap when the value start with '{'

### ISSUE THREAD

**Issue by lowzj** [OpenFeign/feign#539] opened 2017-03-23 02:34 UTC
I'm facing the same problem as the closed issue https://github.com/OpenFeign/feign/issues/470. I commented several days ago and no response received, so I create this issue.

I debug the code and think that there is somewhere a little unreasonable(or I'm wrong). [source](https://github.com/OpenFeign/feign/blob/master/core/src/main/java/feign/ReflectiveFeign.java#L217)

```java
213      RequestTemplate template = resolve(argv, mutable, varBuilder);
214      if (metadata.queryMapIndex() != null) {
215        // add query map parameters after initial resolve so that they take
216        // precedence over any predefined values
217        template = addQueryMapQueryParameters(argv, template);
218     }
```

Method `addQueryMapQueryParameters` in the line 217 is invoked after method `resolve`, and all variables replacement([source](https://github.com/OpenFeign/feign/blob/master/core/src/main/java/feign/RequestTemplate.java#L215)) has been finished in the method `resolve`, and I think there are no variables remaining when invoking `addQueryMapQueryParameters`, so we can not infer that values starting with `{` are variables.

So `addQueryMapQueryParameters` should encode the `QueryMap` keys and values, then put them into query parameters. 
Or making `RequestTemplate` to provide a new `query` method that directly invoking `urlEncode` instead of `encodeIfNotVariable`.

**Comment by adriancole** [comment] 2017-03-23 02:39
this is not an effective way to get support please do not duplicate issues

dupe of #470

**Closed by adriancole** 2017-03-23 02:39 UTC
