### ISSUE TITLE
Can't send Path Params and Body at same request via PUT or POST

### ISSUE THREAD

**Issue by jyoshiriro** [OpenFeign/feign#399] opened 2016-06-02 15:39 UTC
I've seem something at #310, but still occurs.
Feign version: **8.16.2**

**Interface:**

```
public interface MyRequest {
   @RequestLine("PUT /offers/{id}")  // I've also tried "POST", but same problem
   void update(@Param("id") Integer id, OfferRequest offerRequest);
}
```

**Call:**

```
MyRequest request = Feign.builder().encoder(new GsonEncoder()).decoder(new GsonDecoder()).target(MyRequest.class, "http://xxxxx");

OfferRequest offerRequest = new OfferRequest(x, y, z);
request.update(1, offerRequest);
```

**StackTrace:** 

```
Exception in thread "main" java.lang.IllegalStateException: Body parameters cannot be used with form parameters.
    at feign.Util.checkState(Util.java:128)
    at feign.Contract$BaseContract.parseAndValidateMetadata(Contract.java:112)
    at feign.Contract$BaseContract.parseAndValidatateMetadata(Contract.java:64)
    at feign.ReflectiveFeign$ParseHandlersByName.apply(ReflectiveFeign.java:146)
    at feign.ReflectiveFeign.newInstance(ReflectiveFeign.java:53)
    at feign.Feign$Builder.target(Feign.java:198)
    at feign.Feign$Builder.target(Feign.java:194)
```

I know using path param and request body at same request is not a good approach, but the REST API is not our.

**Comment by lolodesbois** [comment] 2016-07-20 15:04
I'm having the same issue using Feign 8.16.2.

Is there any reasons to this hard coded limitation ?

**Comment by jyoshiriro** [comment] 2016-07-20 15:12
My [not elegant, I know] solution was copy the **feign.Contract** Interface to my source and comment out lines 104 and 105.

**Comment by adriancole** [comment] 2016-07-21 01:37
I don't think this limitation is intentional. It seems like a bug

**Comment by adriancole** [comment] 2016-07-21 03:19
I'm so far unable to reproduce this issue
https://github.com/OpenFeign/feign/pull/421

**Comment by csciuto** [comment] 2016-11-15 00:30
I just ran into something similar and I wonder if it might be related.

In my case, the Feign annotation @Param was confused with the Spring Data annotation with the same name. So, since I inadvertently used the Spring version, I hadn't actually specified a Feign path parameter as @Param, so it assumed I wanted it to be a body parameter. Then, the actual unannotated body parameter caused a validation failure.

The error messages Feign generates say the parameters conflict somehow, but doesn't specify details beyond the message signature. Wonder if there would be value in beefing up the error messages to give the state of the validator? If I knew which ones it thought were body parameters and which it thought were form parameters and path parameters, I might've figured it out without debug stepping. Perhaps just return a toString for the MethodMetadata object on validation failures?

**Comment by fd8s0** [comment] 2017-03-29 14:52
It's definitely broken if you use javax.ws.rs.PathParam, but if you switch to feign.Param it works.

**Comment by adriancole** [comment] 2017-03-30 00:41
Hmm can you post an example method definition which breaks? Please dont
cross streams (mix feign and jaxrs annotations as we wouldnt expect that to
work.. not saying you would..)

**Comment by fd8s0** [comment] 2017-03-30 08:57
Sorry it wasn't my code, I just told them to change to the feign annotation and that fixed it, what I can say is they were using jaxrs annotations in other cases and it was working as expected, it was only in this case (mixing requestline put, with a body and jaxrs pathparam) that it wasn't. It seems like a different problem, however it'd be good to recognise if you are seeing cross streams and either support it or not support it but do so explicitly. The error sounded similar but upon reading again it seems like a different thing.
I just thought, because this issue is still open, if everyone was unable to reproduce I'd expect it to be closed.

**Comment by adriancole** [comment] 2017-03-30 09:15
thx I'll close this for now.

Validating jax-rs annotations aren't used from feign-core would be a chicken/egg.

From jax-rs, we could consider checking if any feign-core annotations are in use (as that would be a bug). I'll leave that as an exercise for a contributor with enough interest to do that.

Another way is to use something like error-prone which would make a compile check out of issues like this. It is another form of checking a contract, but it could depend on multiple "contracts" or otherwise be taught what bad is...

**Closed by adriancole** 2017-03-30 09:15 UTC

**Comment by dle-fr** [comment] 2017-05-23 10:23
Hi,

I got the same error with Feign 8.18.0, on a Swagger-codegen generated client (so i cannot modify the client). The annotations used are the good ones (feign.param for path params).

Interface : 

`@RequestLine("POST /client/session/{session_uid}/slot/{slot}/sign")`
  `@Headers({`
    `"Content-Type: application/json",`
    `"Accept: application/json",`
  `})`
  `SignResponse sign(@Param(value="sessionUid", expander=ParamExpander.class) String sessionUid, @Param(value="slot", expander=ParamExpander.class) Integer slot, SignRequest body);`

Error:

`java.lang.IllegalStateException: Body parameters cannot be used with form parameters.`

However, if I change params order (body not last) in the generated code, it works.
